apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.87.1/bundle.yaml
namespace: prometheus-operator
